# Setup
title:               제목입니다.
tagline:             '태그 라인입니다.'
description:         '설명란'
url:                 https://zangzangs.github.io
baseurl:             ''
paginate:            20
permalink:           pretty

# About/contact
author:
  name:              JangHyeon Kim
  url:               https://twitter.com/
  email:             kimjangh94@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
