# Setup
title:               "제목위치"
tagline:             "여기 위치 확인하기"
description:         "장장스의 블로그"
url:                 https://zangzangs.github.io
baseurl:             ''
paginate:            15
permalink:           pretty

# About/contact
author:
  name:              JangHyeon Kim
  url:               https://zangzangs.github.io
  email:             kimjangh94@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
